config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'

  get 'static_pages/about'
  
  get 'sessions/new'

   root 'static_pages#index'

  resources :carts
  resources :users
  resources :games do
   resources :items
  end
  
  get    'items'           => 'items#index'
  get    'game_items'      => 'items#index'
  post   'items'           => 'items#create'
  get    'games'           => 'games#index'
  get    'home'            => 'static_pages#index'
  get    'game_item'       => 'items#show'
  get    'signup'          => 'users#new'
  
  get    'game_edit'       => 'games#edit'
  delete 'game_destroy'    => 'games#destroy'
  
  get    'item_edit'       => 'items#edit'
  patch  'item_edit'       => 'items#update'
  delete 'item_destroy'    => 'items#destroy'
  
  get    'admin_dashboard' => 'admin#index'
  get    'admin_orders'    => 'admin#orders'
  get    'admin_games'     => 'admin#games'
  get    'admin_items'     => 'admin#items'
  get    'admin_quotes'    => 'admin#quotes'
  get    'admin_users'     => 'admin#users'
  
  get    'login'           => 'sessions#new'
  post   'login'           => 'sessions#create'
  delete 'logout'          => 'sessions#destroy'
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_footer.html.erb
<footer class="row" id="footer">
  <div class="large-12 columns">
    <hr/>
    <div class="row">
      <div class="large-6 columns">
        <p>© Griffin Industries, Inc.</p>
      </div>
      <div class="large-6 columns">
        <ul class="inline-list right">
          <li><a href="#">About</a></li>
          <li><a href="#">News</a></li>
          <li><a href="#">Home</a></li>
          <li><a href="#">Sign Up</a></li>
        </ul>
      </div>
    </div>
  </div> 
</footer>

app/views/static_pages/_header.html.erb
<div class="row">
  <div class="large-3 columns" id="logo">
    <h1><%= link_to(image_tag('http://imgur.com/Ltlk9qp.jpg'), home_path) %></h1>
  </div>
  <div class="large-9 columns">
    <ul class="right button-group">
    <li><%= link_to "Games", games_path, class: "button" %></li>
    <li><%= link_to "All Deals", items_path, class: "button" %></li>
    
    <li>
      <%= link_to cart_path(current_user), class: "button"  do %>
        <i class="fa fa-shopping-cart"></i> Cart (0) 
      <% end %>
    </li>
    <% if logged_in? %>
      <button href="#" data-dropdown="drop1" aria-controls="drop1" 
        aria-expanded="false" class="button dropdown"><i class="fa fa-user"></i> 
        <%= current_user.name %></button><br>
      <ul id="drop1" data-dropdown-content class="f-dropdown" aria-hidden="true">
        <% if current_user.admin %>
          <li><%= link_to "Admin Dashboard", admin_dashboard_path %></li>
        <% end %>
        <li><a href="#">Profile</a></li>
        <li><a href="#">Order History</a></li>
        <li><%= link_to "Log Out", logout_path, method: "delete" %></li>
      </ul>
    <% else %>
      <li><%= link_to 'Sign In', login_path, class: 'button' %></li>
    <% end %>
    </ul>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
    <hr>
  </div>
</div>

app/views/static_pages/_quote.html.erb
<p id="quote">
“Out of every one hundred men, ten shouldn't even be there, 
eighty are just targets, nine are the real fighters, and we are lucky to have
them, for they make the battle. Ah, but the one, one is a warrior, and he will 
bring the others back.” - Heraclitus
</p>

app/views/static_pages/_tasks.html.erb
<div id="tasks">
    <div class="panel">
      <div class="panel-body">
        <%= link_to "Browse Games", games_path, class: "btn btn-default" %>
        <br>
        <br>
        <%= link_to "All Deals", items_path, class: "btn btn-default" %>
      </div>
    </div>
</div>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/index.html.erb
<div class="row">
  <div class="large-12 columns">
    <ul class="example-orbit" data-orbit>
      <li>
        <%= image_tag 'http://imgur.com/cVEvXDn.jpg' %>
        <div class="orbit-caption">
          Now selling Elder Scrolls Online gear!
        </div>
      </li>
      <li>
        <%= image_tag 'http://imgur.com/GznyunI.jpg' %>
        <div class="orbit-caption">
          Sale on all Knight Online items: 30% off
        </div>
      </li>
      <li>
        <%= image_tag 'http://imgur.com/fycSvqn.jpg' %>
        <div class="orbit-caption">
          Wtf is this game? Looks nice.
        </div>
      </li>
      <li>
        <%= image_tag 'http://imgur.com/vbAeLRC.jpg' %>
        <div class="orbit-caption">
          Need more runes? You've come to the right place
        </div>
      </li>
    </ul>
    <hr/>
  </div>
</div>

<div class="row">
  <div class="large-4 columns">
    <%= link_to(image_tag('http://imgur.com/LqrObKi.jpg'), games_path) %>
    <h4>Browse By Game</h4>
    <p>Looking for a particular title? Start here to find deals for that game</p>
  </div>
  
  <div class="large-4 columns">
    <%= link_to(image_tag('http://imgur.com/YzDD5Md.jpg'), items_path) %>
    <h4>Browse All Deals</h4>
    <p>Check here if you want to look through all items and services we offer</p>
  </div>
  
  <div class="large-4 columns">
    <%= image_tag 'http://imgur.com/Ikdhtc3.jpg' %>
    <h4>Weekly Deals</h4>
    <p>Save yourself some GP with our deals of the week!</p>
  </div>
</div>

<div class="row">
  <div class="large-12 columns">
  
    <div class="panel">
      <h4>Sign Up!</h4>
          
      <div class="row">
        <div class="large-9 columns">
          <p>Want to hear about great new deals when they are released?</p>
        </div>
        <div class="large-3 columns">
          <%= link_to "Sign Up", signup_path, class: "radius button right" %>
        </div>
      </div>
    </div>
  </div>
</div>
    