config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'

  get 'static_pages/about'
  
  get 'sessions/new'

   root 'static_pages#index'

  resources :carts
  resources :users
  resources :games do
   resources :items
  end
  
  get    'items'           => 'items#index'
  get    'game_items'      => 'items#index'
  post   'items'           => 'items#create'
  get    'games'           => 'games#index'
  get    'home'            => 'static_pages#index'
  get    'game_item'       => 'items#show'
  get    'signup'          => 'users#new'
  
  get    'game_edit'       => 'games#edit'
  delete 'game_destroy'    => 'games#destroy'
  
  get    'item_edit'       => 'items#edit'
  patch  'item_edit'       => 'items#update'
  delete 'item_destroy'    => 'items#destroy'
  
  get    'admin_dashboard' => 'admin#index'
  get    'admin_orders'    => 'admin#orders'
  get    'admin_games'     => 'admin#games'
  get    'admin_items'     => 'admin#items'
  get    'admin_quotes'    => 'admin#quotes'
  get    'admin_users'     => 'admin#users'
  
  get    'login'           => 'sessions#new'
  post   'login'           => 'sessions#create'
  delete 'logout'          => 'sessions#destroy'
  

end

app/views/admin/_game_table.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th>Link</th>
      <th width="150">Image</th>
      <th width="125">Banner</th>
      <th>Modify</th>
    </tr>
  </thead>
  <tbody>
    <% @all_games.each do |game| %>
      <tr>
        <td><%= game.title %></td>
        <td><%= game.slug %></td>
        <td><%= link_to "link", game.link %></td>
        <td><%= image_tag game.image %></td>
        <td><%= image_tag game.banner %></td>
        <td><%= link_to "Edit", '#', data: {:'reveal-id' => "editModal#{game.id}"}%> 
          / <%= link_to "Remove", '#', data: {:'reveal-id' => "removeModal#{game.id}"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<% @all_games.each do |game| %>
  <div id="<%="editModal#{game.id}"%>" class="reveal-modal" data-reveal 
    aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
      <%= render partial: 'games/edit', locals: {game: game}  %>
    <a class="close-reveal-modal">&#215;</a>
  </div>
<% end %>

<% @all_games.each do |game| %>
  <div id="<%="removeModal#{game.id}"%>" class="reveal-modal" data-reveal 
    aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
      <%= render partial: 'games/remove', locals: {game: game}  %>
    <a class="close-reveal-modal">&#215;</a>
  </div>
<% end %>

app/views/admin/_item_table.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Game</th>
      <th width="125">Slug</th>
      <th width="275">Description</th>
      <th>Price</th>
      <th width="125">Image</th>
      <th>Modify</th>
    </tr>
  </thead>
  <tbody>
    <% @all_items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= Game.find(item.game_id).title %></td>
        <td><%= item.slug %></td>
        <td><%= item.description %></td>
        <td><%= "$#{"%5.2f" % item.price}" %></td>
        <td><%= image_tag item.image %></td>
        <td><%= link_to "Edit", '#', data: {:'reveal-id' => "editModal#{item.id}"}%>  
          / <%= link_to "Remove", '#', data: {:'reveal-id' => "removeModal#{item.id}"} %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% @all_items.each do |item| %>
  <div id="<%="editModal#{item.id}"%>" class="reveal-modal" data-reveal 
    aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
      <%= render partial: 'items/edit', locals: {item: item}  %>
    <a class="close-reveal-modal">&#215;</a>
  </div>
<% end %>

<% @all_items.each do |item| %>
  <div id="<%="removeModal#{item.id}"%>" class="reveal-modal" data-reveal 
    aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
      <%= render partial: 'items/remove', locals: {item: item}  %>
    <a class="close-reveal-modal">&#215;</a>
  </div>
<% end %>

app/views/admin/_new_game.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
    
    <%= simple_form_for @game do |f| %>
    
      <%= render 'shared/error_messages' %>
    
      <%= f.input :title %>
      <%= f.input :slug %>
      <%= f.input :link %>
      <%= f.input :image %>
      <%= f.input :banner %>
      </br>
      <div class="large-5 large-centered columns">
        <%= f.button :submit, 'Add Game' %>
      </div>
    <% end %>
    
  </div>
</div>

app/views/admin/_new_item.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
    
    <%= simple_form_for @item do |f| %>
      <%= f.association :game %>
      <%= f.input :title %>
      <%= f.input :slug %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :image, label: 'Image (should be square, ~500x500)' %>
      </br>
      <div class="large-5 large-centered columns">
        <%= f.button :submit, 'Add Item' %>
      </div>
    <% end %>
    
  </div>
</div>

app/views/admin/_sidebar.html.erb
<div class="large-2 large-pull-10 columns">
  <div class="icon-bar vertical five-up">
    <%= link_to admin_dashboard_path, class: "item" do %>
      <i class="fa fa-home"></i>
      <label>Overview</label>
    <% end %>
    <%= link_to admin_orders_path, class: "item" do %>
      <i class="fa fa-book"></i>
      <label>View Orders</label>
    <% end %>
    <%= link_to admin_games_path, class: "item" do %>
      <i class="fa fa-gamepad"></i>
      <label>Add Game</label>
    <% end %>
    <%= link_to admin_items_path, class: "item" do %>
      <i class="fa fa-suitcase"></i>
      <label>Add Item</label>
    <% end %>
    <%= link_to admin_quotes_path, class: "item" do %>
      <i class="fa fa-quote-left"></i>
      <label>Add Quote</label>
    <% end %>
    <%= link_to admin_users_path, class: "item" do %>
      <i class="fa fa-unlock-alt"></i>
      <label>Add Admin</label>
    <% end %>
  </div>
</div>

app/views/admin/games.html.erb
<div class="row">    
   
  <div class="large-10 large-push-2 columns">
    
    
    <h3 class="text-center">Games</h3>
    <br/>
    

    <ul class="accordion" data-accordion="myAccordionGroup">
      <li class="accordion-navigation">
        <a href="#current-games">Current Games</a>
        <div id="current-games" class="content active">
          <%= render 'game_table' %>
        </div>
      </li>
      
      <li class="accordion-navigation">
        <a href="#new-game">Add New Game</a>
        <div id="new-game" class="content">
          <%= render 'new_game' %>
        </div>
      </li>
    </ul>

  </div>
   
  <%= render 'sidebar' %>
  
</div>

app/views/admin/index.html.erb
<div class="row">    
   
  <div class="large-10 large-push-2 columns">
    
    
    <h3 class="text-center">Overview</h3>
    <br/>
    <p>This is the overview section. There will be statistics and graphs and stuff here soon.</p>
    <p>Bacon ipsum dolor amet non occaecat capicola, turkey minim brisket strip steak. Quis meatball cupidatat, andouille do irure fugiat dolore pastrami jerky. Alcatra irure consectetur qui sint leberkas sausage ipsum enim deserunt venison nostrud ut. Eu culpa in, beef enim duis incididunt labore mollit.</p>


  </div>
   
  <%= render 'sidebar' %>
  
</div>
   

app/views/admin/items.html.erb
<div class="row">    
   
  <div class="large-10 large-push-2 columns">
    
    
    <h3 class="text-center">Items</h3>
    <br/>
    

    <ul class="accordion" data-accordion="myAccordionGroup">
      <li class="accordion-navigation">
        <a href="#current-items">Current Items</a>
        <div id="current-items" class="content active">
          <%= render 'item_table' %>
        </div>
      </li>
      
      <li class="accordion-navigation">
        <a href="#new-item">Add New Item</a>
        <div id="new-item" class="content">
          <%= render 'new_item' %>
        </div>
      </li>
    </ul>

  </div>
   
  <%= render 'sidebar' %>
  
</div>

app/views/admin/orders.html.erb
<div class="row">    
   
  <div class="large-10 large-push-2 columns">
    
    
    <h3 class="text-center">Orders</h3>
    <br/>
    <p>This is the orders section. There will be a bunch of orders due to fulfill here soon</p>
    <p>Bacon ipsum dolor amet non occaecat capicola, turkey minim brisket strip steak. Quis meatball cupidatat, andouille do irure fugiat dolore pastrami jerky. Alcatra irure consectetur qui sint leberkas sausage ipsum enim deserunt venison nostrud ut. Eu culpa in, beef enim duis incididunt labore mollit.</p>


  </div>
   
  <%= render 'sidebar' %>
  
</div>
   

app/views/admin/quotes.html.erb
<div class="row">    
   
  <div class="large-10 large-push-2 columns">
    
    
    <h3 class="text-center">Quotes</h3>
    <br/>
    <p>This is the quotes section. There will be tools for adding random quotes here soon</p>
    <p>Bacon ipsum dolor amet non occaecat capicola, turkey minim brisket strip steak. Quis meatball cupidatat, andouille do irure fugiat dolore pastrami jerky. Alcatra irure consectetur qui sint leberkas sausage ipsum enim deserunt venison nostrud ut. Eu culpa in, beef enim duis incididunt labore mollit.</p>


  </div>
   
  <%= render 'sidebar' %>
  
</div>

app/views/admin/users.html.erb
<div class="row">    
   
  <div class="large-10 large-push-2 columns">
    
    
    <h3 class="text-center">Add Admin</h3>
    <br/>
    <p>This is the "Add Admin" section. There will be an interface that lets you turn specific users into admins here soon</p>
    <p>Bacon ipsum dolor amet non occaecat capicola, turkey minim brisket strip steak. Quis meatball cupidatat, andouille do irure fugiat dolore pastrami jerky. Alcatra irure consectetur qui sint leberkas sausage ipsum enim deserunt venison nostrud ut. Eu culpa in, beef enim duis incididunt labore mollit.</p>


  </div>
   
  <%= render 'sidebar' %>
  
</div>