config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'

  get 'static_pages/about'
  
  get 'sessions/new'

   root 'static_pages#index'

  resources :carts
  resources :users
  resources :games do
   resources :items
  end
  
  get    'items'           => 'items#index'
  get    'game_items'      => 'items#index'
  post   'items'           => 'items#create'
  get    'games'           => 'games#index'
  get    'home'            => 'static_pages#index'
  get    'game_item'       => 'items#show'
  get    'signup'          => 'users#new'
  
  get    'game_edit'       => 'games#edit'
  delete 'game_destroy'    => 'games#destroy'
  
  get    'item_edit'       => 'items#edit'
  patch  'item_edit'       => 'items#update'
  delete 'item_destroy'    => 'items#destroy'
  
  get    'admin_dashboard' => 'admin#index'
  get    'admin_orders'    => 'admin#orders'
  get    'admin_games'     => 'admin#games'
  get    'admin_items'     => 'admin#items'
  get    'admin_quotes'    => 'admin#quotes'
  get    'admin_users'     => 'admin#users'
  
  get    'login'           => 'sessions#new'
  post   'login'           => 'sessions#create'
  delete 'logout'          => 'sessions#destroy'
  

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :items
  
  validates :title,  presence: true, length: {maximum:50, minimum: 3 }
  validates :slug,  presence: true, length: {maximum:100 }
  
  def self.ordered
    Game.all.sort_by(&:created_at)
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  
  def index
    @games = Game.ordered
  end
  
  def show
    redirect_to game_items_path(params['id'])  
  end
  
  def create
    @game = Game.new(game_params)
    
    if @game.save
      flash[:success] = "Game Added"
      redirect_to admin_games_path
    else
      flash[:alert] = "Game could not be added"
      redirect_to admin_games_path
    end
  end
  
  def edit
  end
  
  def update
    game = Game.find(params['id'])
    if game.update_attributes(game_params)
      flash[:success] = "Game successfully updated"
      redirect_to admin_games_path
    else
      flash[:alert] = "Game could not be updated"
      redirect_to admin_games_path
    end
  end
  
  def destroy
    Item.where(game_id: params['game_id']).delete_all
    Game.find(params['game_id']).destroy
    flash[:success] = "Game successfully deleted"
    redirect_to admin_games_path
  end
  
  
  def game_params
    params.require(:game).permit(:title, :slug, :link, :image, :banner)
  end
  
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_remove.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
    <h1 class="text-centered">Remove Game</h1>
    <br/>
    <p>Are you sure you want to remove <%= game.title %>?</p>
    <p>This will remove the game and all of its associated items!</p>
    <p>This cannot be undone!</p>
    <br/>
    <%= link_to "I Understand, Blow It Up!", game_destroy_path(game_id: game.id), method: :delete, class: "button" %>
  </div>
</div>

app/views/games/index.html.erb
<% @games.each_with_index do |game, index| %>
  <div class="row">
    <div class="large-12 columns">
      <% unless index == 0 %>
        <hr>
      <% end %>
      <div id="game-logo">
        <%= image_tag game.image %>
      </div>
      <div id="game-info">
        <h2><%= game.title %></h2>
        <p><%= game.slug %></p>
        <%= link_to "View Deals", game_items_path(game), class: "button" %>
      </div>
    </div>
  </div>
<% end %>