config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/index'

  get 'static_pages/about'
  
  get 'sessions/new'

   root 'static_pages#index'

  resources :carts
  resources :users
  resources :games do
   resources :items
  end
  
  get    'items'           => 'items#index'
  get    'game_items'      => 'items#index'
  post   'items'           => 'items#create'
  get    'games'           => 'games#index'
  get    'home'            => 'static_pages#index'
  get    'game_item'       => 'items#show'
  get    'signup'          => 'users#new'
  
  get    'game_edit'       => 'games#edit'
  delete 'game_destroy'    => 'games#destroy'
  
  get    'item_edit'       => 'items#edit'
  patch  'item_edit'       => 'items#update'
  delete 'item_destroy'    => 'items#destroy'
  
  get    'admin_dashboard' => 'admin#index'
  get    'admin_orders'    => 'admin#orders'
  get    'admin_games'     => 'admin#games'
  get    'admin_items'     => 'admin#items'
  get    'admin_quotes'    => 'admin#quotes'
  get    'admin_users'     => 'admin#users'
  
  get    'login'           => 'sessions#new'
  post   'login'           => 'sessions#create'
  delete 'logout'          => 'sessions#destroy'
  

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :game
  
  def self.ordered
    Item.all.sort_by(&:created_at)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def index
    if params['game_id'] then
      @items = Item.where(game_id: params['game_id'])
      @game = Game.find params['game_id']
      
      @banner = @game.banner
      @game_title = @game.title
      @game_desc  = @game.slug
    else
      @items = Item.all
      @banner = "http://imgur.com/DRHFdqg.jpg"
      @game_title = "All Items"
      @game_desc = "View deals from all of our game titles"
    end
  end
  
  def create
    @item = Item.new(item_params)
    
    if @item.save
      flash[:success] = "Item Added"
      redirect_to admin_items_path
    else
      flash[:alert] = "Item could not be added"
      redirect_to admin_items_path
    end
  end
  
  def update
    item = Item.find(params['id'])
    if item.update_attributes(item_params)
      flash[:success] = "Item successfully updated"
      redirect_to admin_items_path
    else
      flash[:alert] = "Item could not be updated"
      redirect_to admin_items_path
    end
  end
  
  def destroy
    Item.find(params['item_id']).destroy
    flash[:success] = "Item successfully deleted"
    redirect_to admin_items_path
  end
  
  def edit
  end
  
  def show
    unless Item.try(:where, id: params['id'], game_id: params['game_id']).empty? then
      @item = Item.where(id: params['id'], game_id: params['game_id']).first
      @game = Game.find params['game_id']
    else
      redirect_to home_path
    end
  end

  def item_params
    params.require(:item).permit(:game_id, :title, :slug, :description, :image, :price)
  end
  
  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_edit.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
    <h1 class="text-centered">Edit Item</h1>
    <%= simple_form_for [Game.find(item.game_id), item] do |f| %>
      <%= f.association :game %>
      <%= f.input :title %>
      <%= f.input :slug %>
      <%= f.input :description %>
      <%= f.input :price %>
      <%= f.input :image, label: 'Image (should be square, ~500x500)' %>
      </br>
      <div class="large-5 large-centered columns">
        <%= f.button :submit, 'Update Item' %>
      </div>
    <% end %>
    
  </div>
</div>

app/views/items/_remove.html.erb
<div class="row">
  <div class="large-6 large-centered columns">
    <h1 class="text-centered">Remove Item</h1>
    <br/>
    <p>Are you sure you want to remove <%= item.title %>?</p>
    <p>This cannot be undone!</p>
    <br/>
    <%= link_to "I Understand, Blow It Up!", item_destroy_path(item_id: item.id), method: :delete, class: "button" %>
  </div>
</div>

app/views/items/index.html.erb
<div class="row">
  <div class="large-12 columns">
  
    <div class="row">
      <div class="large-4 small-12 columns">
      <% if @game then %>
        <ul class="breadcrumbs">
          <li><%= link_to "Home", home_path %></li>
          <li><%= link_to "Games", games_path %></li>
          <li class="current"><%= @game.title %></li>
        </ul>
      <% else %>
        <ul class="breadcrumbs">
          <li><%= link_to "Home", home_path %></li>
          <li><%= link_to "Games", games_path %></li>
          <li class="current">All</li>
        </ul>
      <% end %>
      </div>
    </div>
    
    <div class="row">

      <div class="large-4 small-12 columns">
        <%= image_tag @banner %>
        <div class="hide-for-small panel">
          <h3><%= @game_title %></h3>
          <h5 class="subheader"><%= @game_desc %></h5>
        </div>
      </div>

      <div class="large-8 columns">
          <% @items.each_slice(3) do |slice| %>
            <div class="row">
              <% slice.each do |item| %>
                <div class="large-4 small-6 columns end" id="image-block">
                  <%= image_tag item.image %>
      
                  <div class="panel">
                    <h4 id = "item-title"><%= item.title %></h4>
                    <h6 id = "item-desc"><%= item.slug %></h6>
                    <h6 class="subheader"><%= "$#{"%5.2f" % item.price}" %></h6>
                    <%= link_to "View", game_item_path(item.game_id, item), class: "button" %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
      </div>
      
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="row">
  <div class="large-7 columns">
    <ul class="breadcrumbs">
      <li><%= link_to "Home", home_path %></li>
      <li><%= link_to "Games", games_path %></li>
      <li><%= link_to @game.title, game_items_path(@game) %></li>
      <li class="current"><%= @item.title %></li>
    </ul>
  </div>
</div>

<div class="row">
  <div class="large-7 columns" id="item-image">
    <%= image_tag @item.image %>
  </div>
  <div class="large-5 columns">
    <div id="item-info">
      <h1><%= @item.title %></h1>
      <p><%= @item.description %></p>
    </div>
    <div class="panel" id="checkout">
      <h5 class="large"><strong><%= "$#{"%5.2f" % @item.price}" %></strong></h5>
      <%= link_to "Add to Cart", new_cart_path(id: @item.id), class: "button" %>
    </div>
  </div>
</div>

<div class="row">
  <hr/>
  <div class="large-6 columns">
    <h4>This is a content section.</h4>
    <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa. Boudin aliqua adipisicing rump corned beef.</p>
  </div>
  <div class="large-6 columns">
    <h4>This is a content section.</h4>
    <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
  </div>
</div>

<div class="row">
  <hr>
  <div class="large-12 columns">
    <h4>You might also like:</h4>
    <img src="http://placehold.it/200x150&text=[img]">
    <img src="http://placehold.it/200x150&text=[img]">
    <img src="http://placehold.it/200x150&text=[img]">
    <img src="http://placehold.it/200x150&text=[img]">
  </div>
</div>